"""
block_child_database automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .child_database import ChildDatabase


class BlockChildDatabase(Block):
    child_database: Optional[ChildDatabase] = Field(default=None, alias="child_database")
    pass


