"""
block_heading_1 automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .heading import Heading


class BlockHeading(Block):
    heading__: Optional[Heading] = Field(default=None, alias="heading_1")
    pass


