"""
block automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
import datetime
from .page import Page
from .user import User


class Block(BaseModel):
    object: Optional[str] = Field(default=None, alias="object")
    id: Optional[str] = Field(default=None, alias="id")
    parent: Optional[Page] = Field(default=None, alias="parent")
    created_time: Optional[datetime.datetime] = Field(default=None, alias="created_time")
    last_edited_time: Optional[datetime.datetime] = Field(default=None, alias="last_edited_time")
    created_by: Optional[User] = Field(default=None, alias="created_by")
    last_edited_by: Optional[User] = Field(default=None, alias="last_edited_by")
    has_children: Optional[bool] = Field(default=None, alias="has_children")
    in_trash: Optional[bool] = Field(default=None, alias="in_trash")
    type: Optional[str] = Field(default=None, alias="type")
    pass


