"""
block_image automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .file_object import FileObject


class BlockImage(Block):
    image: Optional[FileObject] = Field(default=None, alias="image")
    pass


