"""
block_numbered_list_item automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .numbered_list_item import NumberedListItem


class BlockNumberedListItem(Block):
    numbered_list_item: Optional[NumberedListItem] = Field(default=None, alias="numbered_list_item")
    pass


