"""
block_bookmark automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .bookmark import Bookmark


class BlockBookmark(Block):
    bookmark: Optional[Bookmark] = Field(default=None, alias="bookmark")
    pass


