"""
block_child_page automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .child_page import ChildPage


class BlockChildPage(Block):
    child_page: Optional[ChildPage] = Field(default=None, alias="child_page")
    pass


