"""
block_bulleted_list_item automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .bulleted_list_item import BulletedListItem


class BlockBulletedListItem(Block):
    bulleted_list_item: Optional[BulletedListItem] = Field(default=None, alias="bulleted_list_item")
    pass


