"""
block_pdf automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .block import Block
from .pdf import PDF
from .pdf_external import PDFExternal
from .pdf_file import PDFFile


class BlockPDF(Block):
    pdf: Optional[Annotated[Union[Annotated[PDFExternal, Tag('external')], Annotated[PDFFile, Tag('file')]], Field(discriminator='type')]
] = Field(default=None, alias="pdf")
    pass


