"""
bookmark automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .rich_text import RichText


class Bookmark(BaseModel):
    caption: Optional[List[RichText]] = Field(default=None, alias="caption")
    url: Optional[str] = Field(default=None, alias="url")
    pass


