"""
callout automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .rich_text import RichText
from .icon import Icon
from .emoji_icon import EmojiIcon
from .file_icon import FileIcon
from .external_icon import ExternalIcon


class Callout(BaseModel):
    rich_text: Optional[List[RichText]] = Field(default=None, alias="rich_text")
    icon: Optional[Annotated[Union[Annotated[EmojiIcon, Tag('emoji')], Annotated[FileIcon, Tag('file')], Annotated[ExternalIcon, Tag('external')]], Field(discriminator='type')]
] = Field(default=None, alias="icon")
    color: Optional[str] = Field(default=None, alias="color")
    pass


