"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .user_tag import UserTag
from .database_tag import DatabaseTag
from .page_tag import PageTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    def user(self) -> UserTag:
        return UserTag(
            self.http_client,
            self.parser
        )

    def database(self) -> DatabaseTag:
        return DatabaseTag(
            self.http_client,
            self.parser
        )

    def page(self) -> PageTag:
        return PageTag(
            self.http_client,
            self.parser
        )



    @staticmethod
    def build(token: str):
        return Client("https://api.notion.com", sdkgen.HttpBearer(token))


    @staticmethod
    def buildAnonymous():
        return Client("https://api.notion.com", sdkgen.Anonymous())
