"""
comment automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .page_id import PageId
from .rich_text import RichText


class Comment(BaseModel):
    parent: Optional[PageId] = Field(default=None, alias="parent")
    discussion_id: Optional[str] = Field(default=None, alias="discussion_id")
    rich_text: Optional[RichText] = Field(default=None, alias="rich_text")
    pass


