"""
database_text automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class DatabaseText(BaseModel):
    content: Optional[str] = Field(default=None, alias="content")
    link: Optional[str] = Field(default=None, alias="link")
    pass


