"""
external_icon automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .icon import Icon
from .external import External


class ExternalIcon(Icon):
    external: Optional[External] = Field(default=None, alias="external")
    pass


