"""
file automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
import datetime


class File(BaseModel):
    url: Optional[str] = Field(default=None, alias="url")
    expiry_time: Optional[datetime.datetime] = Field(default=None, alias="expiry_time")
    pass


