"""
numbered_list_item automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .rich_text import RichText
from .block import Block


class NumberedListItem(BaseModel):
    rich_text: Optional[List[RichText]] = Field(default=None, alias="rich_text")
    color: Optional[str] = Field(default=None, alias="color")
    children: Optional[List[Block]] = Field(default=None, alias="children")
    pass


