"""
page automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
import datetime
from .user import User
from .file_object import FileObject
from .icon import Icon
from .parent_id import ParentId
from .emoji_icon import EmojiIcon
from .file_icon import FileIcon
from .external_icon import ExternalIcon
from .database_parent_id import DatabaseParentId
from .page_parent_id import PageParentId
from .block_parent_id import BlockParentId
from .workspace_parent_id import WorkspaceParentId


class Page(BaseModel):
    object: Optional[str] = Field(default=None, alias="object")
    id: Optional[str] = Field(default=None, alias="id")
    created_time: Optional[datetime.datetime] = Field(default=None, alias="created_time")
    last_edited_time: Optional[datetime.datetime] = Field(default=None, alias="last_edited_time")
    created_by: Optional[User] = Field(default=None, alias="created_by")
    last_edited_by: Optional[User] = Field(default=None, alias="last_edited_by")
    cover: Optional[FileObject] = Field(default=None, alias="cover")
    icon: Optional[Annotated[Union[Annotated[EmojiIcon, Tag('emoji')], Annotated[FileIcon, Tag('file')], Annotated[ExternalIcon, Tag('external')]], Field(discriminator='type')]
] = Field(default=None, alias="icon")
    in_trash: Optional[bool] = Field(default=None, alias="in_trash")
    properties: Optional[Dict[str, Any]] = Field(default=None, alias="properties")
    parent: Optional[Annotated[Union[Annotated[DatabaseParentId, Tag('database_id')], Annotated[PageParentId, Tag('page_id')], Annotated[BlockParentId, Tag('block_id')], Annotated[WorkspaceParentId, Tag('workspace')]], Field(discriminator='type')]
] = Field(default=None, alias="parent")
    url: Optional[str] = Field(default=None, alias="url")
    public_url: Optional[str] = Field(default=None, alias="public_url")
    pass


