"""
parent_id automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .database_parent_id import DatabaseParentId
from .page_parent_id import PageParentId
from .block_parent_id import BlockParentId
from .workspace_parent_id import WorkspaceParentId


class ParentId(BaseModel):
    type: Optional[str] = Field(default=None, alias="type")
    pass


