"""
user_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .user import User


class UserCollection(BaseModel):
    results: Optional[List[User]] = Field(default=None, alias="results")
    next_cursor: Optional[str] = Field(default=None, alias="next_cursor")
    has_more: Optional[bool] = Field(default=None, alias="has_more")
    pass


