"""
user automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .person import Person


class User(BaseModel):
    object: Optional[str] = Field(default=None, alias="object")
    id: Optional[str] = Field(default=None, alias="id")
    type: Optional[str] = Field(default=None, alias="type")
    person: Optional[Person] = Field(default=None, alias="person")
    name: Optional[str] = Field(default=None, alias="name")
    avatar_url: Optional[str] = Field(default=None, alias="avatar_url")
    pass


